# Generated by Django 2.0.3 on 2018-05-03 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20180502_0911'),
        ('user', '0003_auto_20180502_1011'),
    ]

    operations = [
    ]
