# Generated by Django 2.0.3 on 2018-05-01 08:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_content', models.TextField(verbose_name='text_content')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='date_created')),
                ('date_modified', models.DateTimeField(verbose_name='date_modified')),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='restaurant_name')),
                ('category', models.CharField(blank=True, max_length=20, verbose_name='category')),
                ('country', models.CharField(
                    choices=[('Switzerland', 'Switzerland'), ('Germany', 'Germany'), ('France', 'France')],
                    max_length=58, verbose_name='country')),
                ('street', models.CharField(max_length=50, verbose_name='street')),
                ('city', models.CharField(max_length=58, verbose_name='city')),
                ('zip', models.CharField(max_length=10, verbose_name='zip_code')),
                ('website', models.CharField(blank=True, max_length=100, verbose_name='website')),
                ('phone', models.CharField(blank=True, max_length=100, verbose_name='phone')),
                ('email', models.CharField(blank=True, max_length=100, verbose_name='email')),
                ('opening_hours', models.TextField(max_length=1200, verbose_name='opening_hours')),
                ('price_level', models.CharField(
                    choices=[('$', 'very cheap'), ('$$', 'cheap'), ('$$$', 'medium'), ('$$$$', 'expensive'),
                             ('$$$$$', 'very expensive')], max_length=5, verbose_name='price_level')),
                ('image', models.ImageField(blank=True, null=True, upload_to='restaurant_pictures')),
            ],
        ),
        migrations.CreateModel(
            name='RestaurantReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.CharField(
                    choices=[('*', 'Poor'), ('**', 'Acceptable'), ('***', 'Alright!'), ('****', 'Good'),
                             ('*****', 'Excellent')], max_length=10, verbose_name='grade')),
                ('text_content', models.TextField(max_length=300, verbose_name='text_content')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('date_modified', models.DateTimeField(verbose_name='date_modified')),
                ('comments', models.ManyToManyField(blank=True, to='restaurant.Comment', verbose_name='comments')),
                ('like', models.ManyToManyField(blank=True, related_name='user', to=settings.AUTH_USER_MODEL,
                                                verbose_name='like')),
                ('restaurant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE,
                                                 related_name='restaurant_name', to='restaurant.Restaurant',
                                                 verbose_name='restaurant')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users',
                                           to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='review',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review',
                                    to='restaurant.RestaurantReview', verbose_name='review'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_user',
                                    to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
    ]
