# Generated by Django 2.0.3 on 2018-05-01 09:45
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': 'comment', 'verbose_name_plural': 'comments'},
        ),
        migrations.RemoveField(
            model_name='restaurantreview',
            name='comments',
        ),
        migrations.AlterField(
            model_name='comment',
            name='review',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_user', to='restaurant.RestaurantReview', verbose_name='review'),
        ),
        migrations.AlterUniqueTogether(
            name='comment',
            unique_together={('user', 'review')},
        ),
    ]
